### ISSUE TITLE
When i fork this theme i can't search with google

### ISSUE THREAD

**Issue by historiografiadelarteperuano** [aksakalli/jekyll-doc-theme#10]
I forked this theme and i need to implement google search box, but when apply i can't receive anything results.

On google i type:

`welcome site:https://arte-peru.github.io/arte-peru/`  ---> Don't work =(

but i type:

`welcome site:https://aksakalli.github.io/jekyll-doc-theme//`  ---> Work

**Comment by aksakalli** [comment]
Hi @arte-peru ,

The search box is not fetching results from Google or somewhere else. It is just a simple extension called [typeahead.js](https://github.com/twitter/typeahead.js) that returns matching results from the headers. 

It is generated under: https://aksakalli.github.io/jekyll-doc-theme/search.json

It won't work for the search text that is not listed under `search.json`. Besides that, don't forget to clear the local storage of your browser in order to see the new content results while developing.

**Comment by historiografiadelarteperuano** [comment]
Hey, thanks for the answer @aksakalli. But that's no my problem.

I need to add google search box, so i follow this [tutorial](http://digitaldrummerj.me/blogging-on-github-part-7-adding-a-custom-google-search/).

But when apply google search don't respond. But in your template original that works.

Please some hint.
